framework:
    cache:
        pools:
            annonces_cache:
                adapter: 'cache.adapter.redis_tag_aware'
                provider: 'redis://127.0.0.1:6379'
                default_lifetime: 0
