version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - "C:/xampp2/htdocs/winoo/www.winoo.com/annonces/immobilier:/mnt/html/winoo"
    ports:
      - "8080:80"
    environment:
      - APP_ENV=dev
    depends_on:
      - redis  # Dépendance pour que le conteneur PHP démarre après Redis

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: limmobilier_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    depends_on:
      - mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"  # Web interface for viewing emails
      - "1025:1025"  # SMTP server for capturing emails
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.20
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data    
volumes:
  mysql_data:
  esdata:    
