name: Deploy Symfony App (Zero Downtime)

on:
  push:
    branches:
      - test-deploy

jobs:
  deploy:
    runs-on: self-hosted   # Use your self-hosted runner

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Sync only src/ and templates/ to a temporary folder
      - name: Sync files to temporary folder
        run: |
          TMP_DEPLOY=/home/test/deploy_tmp/${GITHUB_RUN_ID}
          mkdir -p $TMP_DEPLOY
          rsync -a --delete ./src/ $TMP_DEPLOY/src/
          rsync -a --delete ./templates/ $TMP_DEPLOY/templates/
          rsync -a --delete ./public/asset $TMP_DEPLOY/public/asset

      # 3️⃣ Deploy synced files to live project
      - name: Move files to live project
        run: |
          APP_PATH=/home/test/public_html
          TMP_DEPLOY=/home/test/deploy_tmp/${GITHUB_RUN_ID}

          # Move src/ and templates/
          rsync -a --delete $TMP_DEPLOY/src/ $APP_PATH/src/
          rsync -a --delete $TMP_DEPLOY/templates/ $APP_PATH/templates/

          # Remove temporary folder
          rm -rf $TMP_DEPLOY

      # 4️⃣ Clear and warmup Symfony cache
      - name: Clear Symfony cache
        run: |
          APP_PATH=/home/test/public_html
          cd $APP_PATH

          php bin/console cache:clear --env=dev || true
          php bin/console cache:warmup --env=dev

          echo "✅ Deployment finished"
