name: Zero-Downtime Symfony Deploy

on:
  push:
    branches:
      - test-deploy

jobs:
  deploy:
    runs-on: self-hosted

    env:
      APP_PATH: /home/test/public_html
      RELEASES_PATH: /home/test/releases
      SHARED_PATH: /home/test/shared
      COMPOSER_ALLOW_SUPERUSER: 1

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Create release folder
      - name: Create release directory
        run: |
          RELEASE_DIR=$RELEASES_PATH/${GITHUB_RUN_ID}
          mkdir -p $RELEASE_DIR

      # 3️⃣ Rsync project files to release folder
      - name: Rsync project
        run: |
          RELEASE_DIR=$RELEASES_PATH/${GITHUB_RUN_ID}
          rsync -a --delete \
            --exclude .git \
            --exclude node_modules \
            --exclude var/log \
            --exclude public/uploads \
            ./ $RELEASE_DIR/

      # 4️⃣ Link shared directories & files
      - name: Link shared directories
        run: |
          RELEASE_DIR=$RELEASES_PATH/${GITHUB_RUN_ID}
          mkdir -p $SHARED_PATH/var/log $SHARED_PATH/public/uploads
          [ -f $SHARED_PATH/.env.local ] || touch $SHARED_PATH/.env.local

          ln -sfn $SHARED_PATH/var/log $RELEASE_DIR/var/log
          ln -sfn $SHARED_PATH/public/uploads $RELEASE_DIR/public/uploads
          ln -sfn $SHARED_PATH/.env.local $RELEASE_DIR/.env.local

      # 5️⃣ Install composer dependencies
      - name: Composer install
        run: |
          RELEASE_DIR=$RELEASES_PATH/${GITHUB_RUN_ID}
          cd $RELEASE_DIR
          composer install --no-dev --optimize-autoloader --no-interaction

      # 6️⃣ Build & warmup Symfony cache
      - name: Warmup Symfony cache
        run: |
          RELEASE_DIR=$RELEASES_PATH/${GITHUB_RUN_ID}
          cd $RELEASE_DIR
          php bin/console cache:clear --env=prod --no-debug || true
          php bin/console cache:warmup --env=prod --no-debug

      # 7️⃣ Run migrations (optional)
      - name: Run Doctrine migrations
        run: |
          RELEASE_DIR=$RELEASES_PATH/${GITHUB_RUN_ID}
          cd $RELEASE_DIR
          php bin/console doctrine:migrations:migrate --no-interaction --env=prod || true

      # 8️⃣ Switch symlink atomically
      - name: Switch current symlink
        run: |
          RELEASE_DIR=$RELEASES_PATH/${GITHUB_RUN_ID}
          ln -sfn $RELEASE_DIR $APP_PATH/current

      # 9️⃣ Cleanup old releases (keep last 3)
      - name: Cleanup old releases
        run: |
          cd $RELEASES_PATH
          ls -1dt */ | tail -n +4 | xargs rm -rf || true

      # 🔟 Done
      - name: Deployment finished
        run: echo "✅ Deployment complete. Zero downtime with rollback support."
