name: Deploy Symfony App (Zero Downtime)

on:
  push:
    branches:
      - test-deploy

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Prepare temporary folder
      - name: Prepare temporary folder
        run: |
          TMP_DEPLOY=/home/test/deploy_tmp/${GITHUB_RUN_ID}
          rm -rf $TMP_DEPLOY
          mkdir -p $TMP_DEPLOY/{src,templates,public/asset}

      # 3️⃣ Sync only changed files to temporary folder
      - name: Sync files to temporary folder
        run: |
          TMP_DEPLOY=/home/test/deploy_tmp/${GITHUB_RUN_ID}
          rsync -a --ignore-existing ./src/ $TMP_DEPLOY/src/
          rsync -a --ignore-existing ./templates/ $TMP_DEPLOY/templates/
          rsync -a --ignore-existing ./public/asset/ $TMP_DEPLOY/public/asset/

      # 4️⃣ Deploy only changed files to live project
      - name: Deploy changed files to live project
        run: |
          APP_PATH=/home/test/public_html
          TMP_DEPLOY=/home/test/deploy_tmp/${GITHUB_RUN_ID}

          # Only copy updated/new files
          rsync -a --update --delete $TMP_DEPLOY/src/ $APP_PATH/src/
          rsync -a --update --delete $TMP_DEPLOY/templates/ $APP_PATH/templates/
          rsync -a --update --delete $TMP_DEPLOY/public/asset/ $APP_PATH/public/asset/

          # Remove temporary folder
          rm -rf $TMP_DEPLOY

      # 5️⃣ Clear and warmup Symfony cache
      - name: Clear Symfony cache
        run: |
          APP_PATH=/home/test/public_html
          cd $APP_PATH

          php bin/console cache:clear --env=dev || true
          php bin/console cache:warmup --env=dev

          echo "✅ Deployment finished"
