name: Deploy Symfony App (Minimal & Safe)

on:
  push:
    branches:
      - test-deploy

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql, xml, curl
          ini-values: post_max_size=256M, upload_max_filesize=256M
          tools: composer:v2

      # 3️⃣ Install Composer dependencies only if composer.json or composer.lock changed
      - name: Check composer changes
        id: composer_check
        run: |
          git fetch origin
          if git diff --name-only origin/main | grep -qE 'composer\.json|composer\.lock'; then
            echo "composer_changed=true" >> $GITHUB_OUTPUT
          else
            echo "composer_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Install Composer dependencies
        if: steps.composer_check.outputs.composer_changed == 'true'
        run: composer install --no-interaction --optimize-autoloader

      # 4️⃣ Run PHPUnit tests
      - name: Run PHPUnit tests
        run: |
          if [ -f ./vendor/bin/phpunit ]; then
            ./vendor/bin/phpunit --stop-on-failure
          else
            echo "No PHPUnit found, skipping tests"
          fi

      # 5️⃣ Sync files to temporary folder
      - name: Sync files to temporary folder
        run: |
          TMP_DEPLOY=/home/test/deploy_tmp/${GITHUB_RUN_ID}
          mkdir -p $TMP_DEPLOY/public/asset
          rsync -a --delete ./src/ $TMP_DEPLOY/src/
          rsync -a --delete ./templates/ $TMP_DEPLOY/templates/
          rsync -a --delete ./public/asset/ $TMP_DEPLOY/public/asset/
          rsync -a --delete ./vendor/ $TMP_DEPLOY/vendor/

      # 6️⃣ Deploy to live project
      - name: Deploy files
        run: |
          APP_PATH=/home/test/public_html
          TMP_DEPLOY=/home/test/deploy_tmp/${GITHUB_RUN_ID}
          rsync -a --delete $TMP_DEPLOY/src/ $APP_PATH/src/
          rsync -a --delete $TMP_DEPLOY/templates/ $APP_PATH/templates/
          rsync -a --delete $TMP_DEPLOY/public/asset/ $APP_PATH/public/asset/
          rsync -a --delete $TMP_DEPLOY/vendor/ $APP_PATH/vendor/
          rm -rf $TMP_DEPLOY

      # 7️⃣ Clear Symfony cache
      - name: Clear Symfony cache
        run: |
          APP_PATH=/home/test/public_html
          cd $APP_PATH
          php bin/console cache:clear || true
          php bin/console cache:warmup
          echo "✅ Deployment finished"
