name: Deploy Symfony App (Zero Downtime)

on:
  push:
    branches:
      - test-deploy

jobs:
  deploy:
    runs-on: self-hosted   # Use your self-hosted runner

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql, xml, curl
          ini-values: post_max_size=256M, upload_max_filesize=256M
          tools: composer:v2

      # 3️⃣ Install dependencies
      - name: Install Composer dependencies
        run: composer install --no-interaction --optimize-autoloader

      # 4️⃣ Run PHPUnit tests
      - name: Run Unit & Functional Tests
        run: |
          echo "Running PHPUnit tests..."
          ./vendor/bin/phpunit --stop-on-failure

      # 5️⃣ Run Static Analysis (optional but recommended)
      - name: Static Analysis
        run: |
          echo "Running PHPStan..."
          ./vendor/bin/phpstan analyse -l max src

      # 6️⃣ Only if tests pass, sync files to temporary folder
      - name: Sync files to temporary folder
        run: |
          TMP_DEPLOY=/home/test/deploy_tmp/${GITHUB_RUN_ID}
          mkdir -p $TMP_DEPLOY
          mkdir -p $TMP_DEPLOY/public
          mkdir -p $TMP_DEPLOY/public/asset
          rsync -a --delete ./src/ $TMP_DEPLOY/src/
          rsync -a --delete ./templates/ $TMP_DEPLOY/templates/
          rsync -a --delete ./public/asset/ $TMP_DEPLOY/public/asset/
          rsync -a --delete ./vendor/ $TMP_DEPLOY/vendor/

      # 7️⃣ Deploy synced files to live project
      - name: Move files to live project
        run: |
          APP_PATH=/home/test/public_html
          TMP_DEPLOY=/home/test/deploy_tmp/${GITHUB_RUN_ID}

          rsync -a --delete $TMP_DEPLOY/src/ $APP_PATH/src/
          rsync -a --delete $TMP_DEPLOY/templates/ $APP_PATH/templates/
          rsync -a --delete $TMP_DEPLOY/public/asset/ $APP_PATH/public/asset/
          rsync -a --delete $TMP_DEPLOY/vendor/ $APP_PATH/vendor/

          rm -rf $TMP_DEPLOY

      # 8️⃣ Clear and warmup Symfony cache
      - name: Clear Symfony cache
        run: |
          APP_PATH=/home/test/public_html
          cd $APP_PATH
          php bin/console cache:clear --env=dev || true
          php bin/console cache:warmup --env=dev
          echo "✅ Deployment finished"
