name: Deploy Symfony App (Zero Downtime)

on:
  push:
    branches:
      - test-deploy

jobs:
  deploy:
    runs-on: self-hosted   # Utilise ton runner installé sur le serveur

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Upload code to server (dans un dossier temporaire)
      - name: Upload files via SCP
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "./"
          target: "/home/test/deploy_tmp/${{ github.run_id }}/"
          overwrite: true
          strip_components: 1

      # 3️⃣ SSH sur le serveur pour finaliser le déploiement
      - name: SSH finalize deployment
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            set -e  # stop on errors

            # Variables
            APP_PATH=/home/test/public_html
            TMP_DEPLOY=/home/test/deploy_tmp/${GITHUB_RUN_ID}
            BACKUP_DIR=$APP_PATH/backups

            mkdir -p $BACKUP_DIR

            # 1️⃣ Backup DB
            TIMESTAMP=$(date +%F-%H-%M-%S)
            mysqldump -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} ${{ secrets.DB_NAME }} > $BACKUP_DIR/db-$TIMESTAMP.sql || true

            # 2️⃣ Installer les dépendances Composer dans un dossier temporaire
            TMP_VENDOR=/tmp/composer_${GITHUB_RUN_ID}
            rm -rf $TMP_VENDOR
            mkdir -p $TMP_VENDOR
            cp $TMP_DEPLOY/composer.* $TMP_VENDOR/
            cd $TMP_VENDOR
            composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist --no-scripts

            # 3️⃣ Déplacer vendor et fichiers sur le projet
            rsync -a --delete $TMP_DEPLOY/ $APP_PATH/
            rsync -a --delete $TMP_VENDOR/vendor/ $APP_PATH/vendor/
            rm -rf $TMP_DEPLOY $TMP_VENDOR

            cd $APP_PATH

            # 4️⃣ Permissions
            mkdir -p var/http_cache
            chown -R www-data:www-data var vendor
            chmod -R 775 var vendor

            # 5️⃣ Cache Symfony
            php bin/console cache:clear --env=prod
            php bin/console cache:warmup --env=prod

            # 6️⃣ Migrations
            php bin/console doctrine:migrations:migrate --no-interaction || true

            # 7️⃣ Reload services
            sudo systemctl reload php8.2-fpm || true
            sudo systemctl reload nginx || true

            echo "✅ Deploy terminé !"
