name: Deploy Symfony App (Self-Hosted)

on:
  push:
    branches:
      - test-deploy

jobs:
  deploy:
    runs-on: self-hosted  # ✅ ton runner privé

    steps:
      # 1️⃣ Checkout GitHub repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Deploy files to public_html
      - name: Deploy code to website folder
        run: |
          APP_PATH="/home/test/public_html"
          echo "📂 Copying files to $APP_PATH..."
          rsync -a --delete --exclude 'vendor/' --exclude 'var/' ./ $APP_PATH/
          echo "✅ Files deployed."
        shell: bash

      # 3️⃣ Backup database
      - name: Backup database
        run: |
          BACKUP_DIR="/home/test/public_html/backups"
          mkdir -p $BACKUP_DIR
          TIMESTAMP=$(date +%F-%H-%M-%S)
          echo "💾 Backing up DB to $BACKUP_DIR/db-$TIMESTAMP.sql"
          mysqldump -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} ${{ secrets.DB_NAME }} > $BACKUP_DIR/db-$TIMESTAMP.sql || true
          # Keep last 7 backups
          ls -1tr $BACKUP_DIR/db-*.sql | head -n -7 | xargs -d '\n' rm -f --
        shell: bash

      # 4️⃣ Install Composer dependencies & Symfony cache
      - name: Install dependencies and warmup cache
        run: |
          cd /home/test/public_html
          composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist
          mkdir -p var/http_cache
          chown -R www-data:www-data var
          chmod -R 775 var
          php bin/console cache:clear --env=prod
          php bin/console cache:warmup --env=prod
        shell: bash

      # 5️⃣ Run Doctrine migrations
      - name: Run Doctrine Migrations
        run: |
          cd /home/test/public_html
          php bin/console doctrine:migrations:migrate --no-interaction || true
        shell: bash
