name: Zero-Downtime Symfony Deploy (Single Release)

on:
  push:
    branches:
      - test-deploy

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Prepare release folder
      - name: Prepare release folder
        run: |
          RELEASE_DIR=/home/test/releases/${GITHUB_RUN_ID}
          mkdir -p $RELEASE_DIR

      # 3️⃣ Rsync project to release folder
      - name: Sync project to release folder
        run: |
          RELEASE_DIR=/home/test/releases/${GITHUB_RUN_ID}
          rsync -a --delete --exclude .git --exclude tmp --exclude var/cache --exclude node_modules ./ $RELEASE_DIR/

      # 4️⃣ Install composer dependencies
      - name: Composer install
        run: |
          RELEASE_DIR=/home/test/releases/${GITHUB_RUN_ID}
          cd $RELEASE_DIR
          composer install --no-dev --optimize-autoloader

      # 5️⃣ Clear and warmup Symfony cache
      - name: Clear Symfony cache
        run: |
          RELEASE_DIR=/home/test/releases/${GITHUB_RUN_ID}
          cd $RELEASE_DIR
          php bin/console cache:clear --env=prod || true
          php bin/console cache:warmup --env=prod

      # 6️⃣ Switch symlink to new release
      - name: Switch live release
        run: |
          APP_PATH=/home/test/public_html
          RELEASE_DIR=/home/test/releases/${GITHUB_RUN_ID}

          # Remove previous release
          if [ -L $APP_PATH/current ]; then
            OLD_RELEASE=$(readlink $APP_PATH/current)
            rm -rf $OLD_RELEASE
          fi

          # Atomically switch symlink
          ln -sfn $RELEASE_DIR $APP_PATH/current

      - name: Deployment finished
        run: echo "✅ Deployment complete. Only the last release is kept."
