name: Partial Symfony Deploy (Templates & Assets)

on:
  push:
    branches:
      - test-deploy

jobs:
  deploy:
    runs-on: self-hosted

    env:
      APP_PATH: /home/test/public_html

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Rsync only modified directories
      - name: Sync modified files
        run: |
          rsync -a --delete ./templates/ $APP_PATH/templates/
          rsync -a --delete ./src/ $APP_PATH/src/
          rsync -a --delete ./public/asset/ $APP_PATH/public/asset/

      # 3️⃣ Clear Symfony cache
      - name: Clear Symfony cache
        run: |
          cd $APP_PATH
          php bin/console cache:clear --env=prod --no-debug || true
          php bin/console cache:warmup --env=prod --no-debug

      # 4️⃣ Deployment finished
      - name: Done
        run: echo "✅ Partial deploy finished: only templates/src/assets updated"
